### ISSUE TITLE
Multiple object output in JupyterLab

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/histbook#52]
Currently, the README advises to just drop `.to(canvas)` call and let jupyterlab try to display the histogram object. Often times it is convenient to output multiple histograms from the same cell. For that case one can use
```python
from IPython.display import display
display(histogram.step("data"))
```
I think many people would want to know about that. Even further, it would make sense to unify interface for this. I think something like this can be implemented as a part of `histbook.vega`:
```python
import numpy
from histbook import *
from IPython.display import display
class VegaJson:
    def __init__(self, x):
        self._mimejson = {"application/vnd.vegalite.v2+json": x}
    def _repr_mimebundle_(self, **kwargs):
        return self._mimejson
canvas = lambda x: display(VegaJson(x))

array = numpy.random.normal(0, 1, 1000000)
histogram = Hist(bin("data", 10, -5, 5))
histogram.fill(data=array)
histogram.step("data").to(canvas)
```
What do you think about this?

**Comment by veprbl** [comment]
> Just to let you know, the future of histbook is uncertain because I learned about the existence of Boost.Histogram and Physt, both excellent histogramming libraries available in Python. 

I remember that you say that you'd rather contribute ideas than maintain a code, but I fail to understand how any of these packages can cover functionality of histbook.

> ```python
> histogram.step("data1")
> histogram.step("data2")
> histogram.step("data3")
> ```
> 
> ought to get you three displays, no?

Ofcourse not. It happens for the same reason why
```python
1
2
3
```
gives only 3

**Comment by veprbl** [comment]
> and there was no way to make it work in both Lab and Notebook

I think I'm proposing exactly the way to do that.

**Comment by jpivarski** [comment]
Last I tried it, Notebook ignored the Vega mimetype.

**Comment by veprbl** [comment]
@jpivarski Absolutely. I meant that both Notebook and Lab to use `.to(canvas)`.

**Comment by jpivarski** [comment]
I haven't yet wrapped my head around how this makes it work for Notebook (since Notebook required a custom-Javascript solution, `pyvega`, which isn't allowed in Lab, and then it overrides the mimetype— that's why I couldn't have both). However, if it does work, then congratulations (!) and could you submit a pull request?

To keep you aware of developments, I've been working on a cross-library, cross-language histogram RPC format with all the bells and whistles so that histograms from any histogramming library can be encoded in it. Then we can let Boost.Histogram becomes the best filler, Physt be the best plotter, etc. This is [histos](https://github.com/diana-hep/histos) (from the Greek; we had a long exchange about the etymology of the name "histogram").

I also (just this morning) got rights to the pip name "hist". I might put a nice front-end to histos in a package that can be installed with "pip install hist" that would take most of the functionality of histbook. The one thing that would be held back is histbook's call-graph optimization of expressions— this rightly belongs in a computation engine like [awkward-array](https://github.com/scikit-hep/awkward-array).
